namespace Acs.Acr122u.Models;

/// <summary>
/// A parsed ATR (Answer To Reset), as generated by the ACR122U for a detected PICC (§3.1).
/// </summary>
public sealed class AtrInfo
{
    /// <summary>The raw, unparsed ATR bytes.</summary>
    public required byte[] Raw { get; init; }

    /// <summary>The recognized card kind, or <see cref="CardKind.Unknown"/> if it could not be determined.</summary>
    public required CardKind Kind { get; init; }

    /// <summary>
    /// For ISO 14443-4 tags (§3.1.2), the historical bytes carried in the ATR (derived from the
    /// tag's ATS for Type A, or from the ATTRIB response for Type B). <see langword="null"/> for
    /// tags recognized via the §3.1.1 card-name encoding.
    /// </summary>
    public byte[]? HistoricalBytes { get; init; }

    /// <summary>
    /// Parses a raw ATR according to the layouts documented in §3.1.1 (ISO 14443 Part 3 PICCs —
    /// MIFARE, FeliCa, Topaz/Jewel) and §3.1.2 (ISO 14443 Part 4 PICCs).
    /// </summary>
    public static AtrInfo Parse(ReadOnlySpan<byte> atr)
    {
        if (atr.Length < 5 || atr[0] != 0x3B)
        {
            return new AtrInfo { Raw = atr.ToArray(), Kind = CardKind.Unknown };
        }

        // §3.1.1: byte[4] == 0x80 flags an optional COMPACT-TLV status indicator, and RID
        // A0 00 00 03 06h identifies the PC/SC workgroup "card name" encoding used to recognize
        // MIFARE/FeliCa/Topaz tags (see the example ATR for a MIFARE 1K card in the spec).
        if (atr.Length >= 15 && atr[4] == 0x80 && atr[5] == 0x4F && atr[6] == 0x0C &&
            atr[7] == 0xA0 && atr[8] == 0x00 && atr[9] == 0x00 && atr[10] == 0x03 && atr[11] == 0x06)
        {
            var cardNameHigh = atr[13];
            var cardNameLow = atr[14];
            var kind = (cardNameHigh, cardNameLow) switch
            {
                (0x00, 0x01) => CardKind.MifareClassic1K,
                (0x00, 0x02) => CardKind.MifareClassic4K,
                (0x00, 0x03) => CardKind.MifareUltralight,
                (0x00, 0x26) => CardKind.MifareMini,
                (0xF0, 0x04) => CardKind.TopazOrJewel,
                (0xF0, 0x11) => CardKind.FeliCa212K,
                (0xF0, 0x12) => CardKind.FeliCa424K,
                _ => CardKind.Unknown,
            };

            return new AtrInfo { Raw = atr.ToArray(), Kind = kind };
        }

        // §3.1.2: ISO 14443-4 tags carry ATS/ATTRIB-derived historical bytes instead of a card name.
        var historicalCount = atr[1] & 0x0F;
        var historical = historicalCount > 0 && atr.Length >= 4 + historicalCount
            ? atr.Slice(4, historicalCount).ToArray()
            : null;

        return new AtrInfo { Raw = atr.ToArray(), Kind = CardKind.Iso14443Part4, HistoricalBytes = historical };
    }
}
